---
version: "2.1"
services:
  installer:
    image: nicholaswilde/novnc:latest
    container_name: novnc
    ports:
      - 6080:6080
    restart: unless-stopped
    volumes:
      - app:/app
volumes:
  app:
