---
version: "2.1"
services:
  installer:
    image: nicholaswilde/template:latest
    container_name: template
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - app:/app
      - config:/config
      - defaults:/defaults
volumes:
  app:
  config:
  defaults:
